# Generated by Django 5.2.4 on 2025-07-28 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_theme', models.TextField(max_length=30, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(30)])),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
