# Generated by Django 5.2.4 on 2025-07-30 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmodel',
            name='question',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='helpmodel',
            name='question_theme',
            field=models.TextField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
