# Generated by Django 5.2.4 on 2025-07-31 18:32

import common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_helpmodel_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNoProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField()),
                ('telephone_number', models.CharField(validators=[common.validators.number_validator])),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField()),
                ('telephone_number', models.CharField(validators=[common.validators.number_validator])),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(validators=[django.core.validators.MinLengthValidator(3)])),
                ('delivery_choices', models.CharField(choices=[('ECONT', 'ECONT'), ('SPEEDY', 'SPEEDY')])),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
