# Generated by Django 5.2.4 on 2025-07-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cpu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='base_clock',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='boost_clock',
        ),
    ]
