# Generated by Django 5.2.4 on 2025-07-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cpu_base_clock_remove_cpu_boost_clock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='l3_cache',
            new_name='cache',
        ),
    ]
