# Generated by Django 5.2.4 on 2025-07-30 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_gpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltComputers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('image', models.URLField()),
                ('ram', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(10)])),
                ('gpu', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(10)])),
                ('motherboard', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cpu', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(10)])),
                ('box', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('storage', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('image', models.URLField()),
                ('platform', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
                ('socket', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('chipset', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('image', models.URLField()),
                ('type', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('frequency', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('megahertz', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='bus',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_type',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
