# Generated by Django 5.2.4 on 2025-07-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_builtcomputers_motherboard_ram_alter_cpu_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='megahertz',
            new_name='size',
        ),
    ]
