# Generated by Django 5.2.4 on 2025-07-30 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_megahertz_ram_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='frequency',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
