# Generated by Django 5.2.4 on 2025-07-30 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_ram_frequency_alter_ram_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='frequency',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
