# Generated by Django 5.2.4 on 2025-07-30 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_ram_frequency_alter_ram_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builtcomputers',
            name='box',
        ),
        migrations.AlterField(
            model_name='builtcomputers',
            name='cpu',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='builtcomputers',
            name='gpu',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='builtcomputers',
            name='motherboard',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='builtcomputers',
            name='ram',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='builtcomputers',
            name='storage',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
