# Generated by Django 5.2.4 on 2025-08-05 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_builtcomputers_box_alter_builtcomputers_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='memory_type',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
