# Generated by Django 5.2.4 on 2025-08-05 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_gpu_memory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='memory',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
